<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class CatsBasicosSeeder extends Seeder
{
    public function run()
    {
$materias = [
    ['id' => 1, 'materia' => 'CIVIL', 'adicionales' => null],
    ['id' => 2, 'materia' => 'MERCANTIL', 'adicionales' => null],
    ['id' => 3, 'materia' => 'FAMILIAR', 'adicionales' => null],
    ['id' => 4, 'materia' => 'MIXTO', 'adicionales' => null],
    ['id' => 5, 'materia' => 'LABORAL', 'adicionales' => null],
];
DB::table('materias')->insert($materias);

$organos = [
    ['id' => 1, 'IdMateria' => 1, 'organo' => '1° CIVIL', 'adicionales' => null],
    ['id' => 2, 'IdMateria' => 2, 'organo' => '1° MERCANTIL', 'adicionales' => null],
    ['id' => 3, 'IdMateria' => 3, 'organo' => '1° ORAL FAM', 'adicionales' => null],
    ['id' => 4, 'IdMateria' => 2, 'organo' => '1° ORAL MERCA', 'adicionales' => null],
    ['id' => 5, 'IdMateria' => 3, 'organo' => '1°ORAL FAM VESP', 'adicionales' => null],
    ['id' => 6, 'IdMateria' => 3, 'organo' => '10° ORAL FAM', 'adicionales' => null],
    ['id' => 7, 'IdMateria' => 1, 'organo' => '2° CIVIL', 'adicionales' => null],
    ['id' => 8, 'IdMateria' => 2, 'organo' => '2° MERCANTIL', 'adicionales' => null],
    ['id' => 9, 'IdMateria' => 3, 'organo' => '2°ORAL FAM VESP', 'adicionales' => null],
    ['id' => 10, 'IdMateria' => 1, 'organo' => '3° CIVIL', 'adicionales' => null],
    ['id' => 11, 'IdMateria' => 2, 'organo' => '3° MERCANTIL', 'adicionales' => null],
    ['id' => 12, 'IdMateria' => 4, 'organo' => '3° MIXTO DE LO CIVIL, MOTUL', 'adicionales' => null],
    ['id' => 13, 'IdMateria' => 3, 'organo' => '3° ORAL FAM VESP', 'adicionales' => null],
    ['id' => 14, 'IdMateria' => 3, 'organo' => '3°ORAL FAM VESP', 'adicionales' => null],
    ['id' => 15, 'IdMateria' => 4, 'organo' => '3RO MIXTO MOTUL', 'adicionales' => null],
    ['id' => 16, 'IdMateria' => 1, 'organo' => '4° CIVIL', 'adicionales' => null],
    ['id' => 17, 'IdMateria' => 2, 'organo' => '4° MERCANTIL', 'adicionales' => null],
    ['id' => 18, 'IdMateria' => 4, 'organo' => '4TO MIXTO DE LO CIVIL Y MERCANTIL DEL 1ER DEPARTAMENTO JUDICIAL DEL ESTADO', 'adicionales' => null],
    ['id' => 19, 'IdMateria' => 3, 'organo' => '4TO ORAL FAM MAT', 'adicionales' => null],
    ['id' => 20, 'IdMateria' => 1, 'organo' => '5° CIVIL', 'adicionales' => null],
    ['id' => 21, 'IdMateria' => 3, 'organo' => '5° ORAL FAM', 'adicionales' => null],
    ['id' => 22, 'IdMateria' => 4, 'organo' => '5TO MIXTO IZAMAL', 'adicionales' => null],
    ['id' => 23, 'IdMateria' => 3, 'organo' => '5TO ORAL FAM MAT', 'adicionales' => null],
    ['id' => 24, 'IdMateria' => 3, 'organo' => '6°ORAL FAM', 'adicionales' => null],
    ['id' => 25, 'IdMateria' => 3, 'organo' => '6°ORAL FAMILIAR', 'adicionales' => null],
    ['id' => 26, 'IdMateria' => 3, 'organo' => '7°ORAL FAMILIAR', 'adicionales' => null],
    ['id' => 27, 'IdMateria' => 3, 'organo' => '8° ORAL FAM', 'adicionales' => null],
    ['id' => 28, 'IdMateria' => 3, 'organo' => '8°ORAL FAMILIAR', 'adicionales' => null],
    ['id' => 29, 'IdMateria' => 3, 'organo' => '9°ORAL FAM', 'adicionales' => null],
    ['id' => 30, 'IdMateria' => 5, 'organo' => 'JUNTA 1', 'adicionales' => null],
    ['id' => 31, 'IdMateria' => 5, 'organo' => 'JUNTA 3', 'adicionales' => null],
    ['id' => 32, 'IdMateria' => 5, 'organo' => 'JUNTA 4', 'adicionales' => null],
    ['id' => 33, 'IdMateria' => 2, 'organo' => 'JUZGADO DE DISTRITO MERCANTIL', 'adicionales' => null],
    ['id' => 34, 'IdMateria' => 5, 'organo' => 'TRIB 2 LABORAL', 'adicionales' => null],
];
DB::table('organos')->insert($organos);  

$personas = [
    ['id' => 1, 'persona' => 'ACEVEDO GODOY ORLANDO DE JESUS Y JAVIER FRANCISCO PERERA LOPEZ', 'generales' => null, 'adicionales' => null],
    ['id' => 2, 'persona' => 'ACEVEDO MORON ORLANDO DE JESUS Y JAVIER FRANCISCO PERERA LOPEZ', 'generales' => null, 'adicionales' => null],
    ['id' => 3, 'persona' => 'ALEJANDRO AZAEL CUTZ COLLI', 'generales' => null, 'adicionales' => null],
    ['id' => 4, 'persona' => 'ALFREDO CAMARA MENDEZ', 'generales' => null, 'adicionales' => null],
    ['id' => 5, 'persona' => 'ANCONA BAQUEIRO KARINA', 'generales' => null, 'adicionales' => null],
    ['id' => 6, 'persona' => 'ANGEL GABRIEL SANCHEZ CU', 'generales' => null, 'adicionales' => null],
    ['id' => 7, 'persona' => 'ARGAEZ CANCHE IRVING ALEXIS', 'generales' => null, 'adicionales' => null],
    ['id' => 8, 'persona' => 'ARRENDADORA VE POR MAS', 'generales' => null, 'adicionales' => null],
    ['id' => 9, 'persona' => 'AVILES DIAZ PETRONA VALENTINA', 'generales' => null, 'adicionales' => null],
    ['id' => 10, 'persona' => 'BANAMEX', 'generales' => null, 'adicionales' => null],
    ['id' => 11, 'persona' => 'BANORTE', 'generales' => null, 'adicionales' => null],
    ['id' => 12, 'persona' => 'BARCELO SOSA LUIS FELIPE Y OSALDE VILLANUEVA KARLA KARIME', 'generales' => null, 'adicionales' => null],
    ['id' => 13, 'persona' => 'BASILIO HUCHIN ARGAEZ', 'generales' => null, 'adicionales' => null],
    ['id' => 14, 'persona' => 'BASTARRACHEA ILIBARRI JORGE ANDRES Y VIDIA ANDREA BASTARRACHEA ULIBARRI', 'generales' => null, 'adicionales' => null],
    ['id' => 15, 'persona' => 'BBVA', 'generales' => null, 'adicionales' => null],
    ['id' => 16, 'persona' => 'BBVA (AHORA YA ES DE BANORTE)', 'generales' => null, 'adicionales' => null],
    ['id' => 17, 'persona' => 'BG EXPORTACIONES DEL CARIBE SA DE CV CARLOS ESTEBAN AVILA QUINTERO', 'generales' => null, 'adicionales' => null],
    ['id' => 18, 'persona' => 'BOLIO MIER Y TERAN LUIS FELIPE', 'generales' => null, 'adicionales' => null],
    ['id' => 19, 'persona' => 'BORGES BADUY JORGE CARLOS', 'generales' => null, 'adicionales' => null],
    ['id' => 20, 'persona' => 'BRICEÑO MARTIN ENRIQUE GUADALUPE', 'generales' => null, 'adicionales' => null],
    ['id' => 21, 'persona' => 'BURGOS ESPOSITOS CARLOS HUMBERTO', 'generales' => null, 'adicionales' => null],
    ['id' => 22, 'persona' => 'BURGOS ESPOSITOS FERNANDO MANUEL y MAGAÑA LEON DAVID ISRAEL', 'generales' => null, 'adicionales' => null],
    ['id' => 23, 'persona' => 'CAMARA CHAVIANO ALFREDO JOSE ALEJANDRO MOLINA MEX', 'generales' => null, 'adicionales' => null],
    ['id' => 24, 'persona' => 'CAMARA MENDEZ ALFREDO', 'generales' => null, 'adicionales' => null],
    ['id' => 25, 'persona' => 'CAMARA MENDEZ IVAN ALFREDO', 'generales' => null, 'adicionales' => null],
    ['id' => 26, 'persona' => 'CAMARA MENDEZ RODRIGO ALBERTO y BASULTO CAN JOSE LAURIANO', 'generales' => null, 'adicionales' => null],
    ['id' => 27, 'persona' => 'CAMARA MENDEZ RODRIGO ALBERTO; Y CORAL MAGAÑA PABLO EMILIO', 'generales' => null, 'adicionales' => null],
    ['id' => 28, 'persona' => 'CAMARA RUIZ RODRIGO ALBERTO', 'generales' => null, 'adicionales' => null],
    ['id' => 29, 'persona' => 'CAMPOS CABRERA FRANCISCO JAVIER', 'generales' => null, 'adicionales' => null],
    ['id' => 30, 'persona' => 'CAN GAMBOA MANUELITA JESUS', 'generales' => null, 'adicionales' => null],
    ['id' => 31, 'persona' => 'CANTO AMAYA DIDIER ISAI', 'generales' => null, 'adicionales' => null],
    ['id' => 32, 'persona' => 'CANTO BORGES ANGELINA', 'generales' => null, 'adicionales' => null],
    ['id' => 33, 'persona' => 'CANTO CACERES JORGE LUIS, JORGE ALEXIS QUIJANO RODRIGUEZ', 'generales' => null, 'adicionales' => null],
    ['id' => 34, 'persona' => 'CARDIN MARTINEZ DANIEL', 'generales' => null, 'adicionales' => null],
    ['id' => 35, 'persona' => 'CARRILLO CASTRO LOURDES ADRIANA', 'generales' => null, 'adicionales' => null],
    ['id' => 36, 'persona' => 'CARVAJAL CRUZ RANDY, y MIER Y TERAN CAMARA RICARDO JOSE', 'generales' => null, 'adicionales' => null],
    ['id' => 37, 'persona' => 'CASTRO MAGAÑA MARIA PIEDAD SUC TEST', 'generales' => null, 'adicionales' => null],
    ['id' => 38, 'persona' => 'CEBALLOS RAMIREZ MARLING MARTINA Y OTROS', 'generales' => null, 'adicionales' => null],
    ['id' => 39, 'persona' => 'COCOM CANCHE GEISY MARGARITA', 'generales' => null, 'adicionales' => null],
    ['id' => 40, 'persona' => 'COCOM GUZMAN JOSE GASPAR', 'generales' => null, 'adicionales' => null],
    ['id' => 41, 'persona' => 'COLLI LORIA DELFINO', 'generales' => null, 'adicionales' => null],
    ['id' => 42, 'persona' => 'CONCHA PAREDES JOSUE ISAAC', 'generales' => null, 'adicionales' => null],
    ['id' => 43, 'persona' => 'CORAL MAGAÑA PABLO EMILIO', 'generales' => null, 'adicionales' => null],
    ['id' => 44, 'persona' => 'CORTAZAR FONZ PEDRO RAMON', 'generales' => null, 'adicionales' => null],
    ['id' => 45, 'persona' => 'CRUZ PINTO SANTOS RAMON Y SANCHEZ CAMPOS GUADALUPE', 'generales' => null, 'adicionales' => null],
    ['id' => 46, 'persona' => 'CHAN MANZANILLA JUAN CARLOS', 'generales' => null, 'adicionales' => null],
    ['id' => 47, 'persona' => 'CHI COLLI MARIA LOURDES', 'generales' => null, 'adicionales' => null],
    ['id' => 48, 'persona' => 'CHIM SANCHEZ DIANA BEATRIZ', 'generales' => null, 'adicionales' => null],
    ['id' => 49, 'persona' => 'DALIA DEL CARMEN RODRIGUEZ MEDINA; PAOLA CONCEPCION GUILLERMO RODRIGUEZ', 'generales' => null, 'adicionales' => null],
    ['id' => 50, 'persona' => 'DESARROLLO INMOBILIARIO SOSTENIBLE', 'generales' => null, 'adicionales' => null],
    ['id' => 51, 'persona' => 'DIANA RUBI FRANCO DE LA CRUZ', 'generales' => null, 'adicionales' => null],
    ['id' => 52, 'persona' => 'DIAZ CASTRO MARIA JOSEFA', 'generales' => null, 'adicionales' => null],
    ['id' => 53, 'persona' => 'DIAZ CASTRO MARIA JOSEFA SUC INT', 'generales' => null, 'adicionales' => null],
    ['id' => 54, 'persona' => 'EDEMAR EMILIO RODRIGUEZ LOPEZ', 'generales' => null, 'adicionales' => null],
    ['id' => 55, 'persona' => 'EDUARDO PASCUAL CABRERA SOBERANIS y MARLENE GENOVEVA ORTIZ OCAÑA', 'generales' => null, 'adicionales' => null],
    ['id' => 56, 'persona' => 'ESCAM DEL SURESTE SA DE CV / MAY HOIL JUAN MANUEL', 'generales' => null, 'adicionales' => null],
    ['id' => 57, 'persona' => 'ESTEBAN FERNANDO POOT DZUL Y OTRA', 'generales' => null, 'adicionales' => null],
    ['id' => 58, 'persona' => 'FERRERA SANTIAGO AIDA DEL CARMEN', 'generales' => null, 'adicionales' => null],
    ['id' => 59, 'persona' => 'FLETES GUADALAJARA MERIDA SA DE CV', 'generales' => null, 'adicionales' => null],
    ['id' => 60, 'persona' => 'FRANCO DE LA CRUZ DIANA RUBI', 'generales' => null, 'adicionales' => null],
    ['id' => 61, 'persona' => 'GG DEL SURESTE Y GIJON MOLINA JORGE EDUARDO', 'generales' => null, 'adicionales' => null],
    ['id' => 62, 'persona' => 'GIJON MOLINA JORGE EDUARDO', 'generales' => null, 'adicionales' => null],
    ['id' => 63, 'persona' => 'GIJON MOLINA RICARDO DE JESUS', 'generales' => null, 'adicionales' => null],
    ['id' => 64, 'persona' => 'GLORIA ESTHER COOL MONTEJO', 'generales' => null, 'adicionales' => null],
    ['id' => 65, 'persona' => 'GONZALEZ RIVERO JORGE ALFONSO', 'generales' => null, 'adicionales' => null],
    ['id' => 66, 'persona' => 'GOROCICA DIAZ RUDY JESUS', 'generales' => null, 'adicionales' => null],
    ['id' => 67, 'persona' => 'GUERRERO ALVAREZ PABLO', 'generales' => null, 'adicionales' => null],
    ['id' => 68, 'persona' => 'GUERRERO CAMPOS BEATRIZ EUGENIA Y CASTILLO SERRANO GABRIELA', 'generales' => null, 'adicionales' => null],
    ['id' => 69, 'persona' => 'HERNANDEZ ARCE JOAQUIN ALFREDO', 'generales' => null, 'adicionales' => null],
    ['id' => 70, 'persona' => 'HUCHIN ARGAEZ ARSENIO Y CHI COLLI JESUS ABNEMAR', 'generales' => null, 'adicionales' => null],
    ['id' => 71, 'persona' => 'HUCHIN ARGAEZ BASILIO', 'generales' => null, 'adicionales' => null],
    ['id' => 72, 'persona' => 'ILEANA VALERIA RAVELL CANUL', 'generales' => null, 'adicionales' => null],
    ['id' => 73, 'persona' => 'INFONAVIT', 'generales' => null, 'adicionales' => null],
    ['id' => 74, 'persona' => 'JAVIER FRANCISCO PERERA LOPEZ', 'generales' => null, 'adicionales' => null],
    ['id' => 75, 'persona' => 'JESUS DORANTES VAZQUEZ Y OTROS', 'generales' => null, 'adicionales' => null],
    ['id' => 76, 'persona' => 'JESUS EDUARDO MARTIN TUYUB Y OTROS', 'generales' => null, 'adicionales' => null],
    ['id' => 77, 'persona' => 'JORGE ALEXIS QUIJANO RODRIGUEZ', 'generales' => null, 'adicionales' => null],
    ['id' => 78, 'persona' => 'JORGE ANDRES BASTARRACHEA ULIBARRI y ANDREA BASTARRACHEA ULIBARRI', 'generales' => null, 'adicionales' => null],
    ['id' => 79, 'persona' => 'JORGE GIJON MOLINA', 'generales' => null, 'adicionales' => null],
    ['id' => 80, 'persona' => 'JOSE CARLOS RODRIGUEZ CASA SAN JOSE', 'generales' => null, 'adicionales' => null],
    ['id' => 81, 'persona' => 'JOSE MAURICIO VELAZQUEZ PULIDO', 'generales' => null, 'adicionales' => null],
    ['id' => 82, 'persona' => 'JULIA ALICIA VALDEZ TEC', 'generales' => null, 'adicionales' => null],
    ['id' => 83, 'persona' => 'KU OXTE ALMA LUISA', 'generales' => null, 'adicionales' => null],
    ['id' => 84, 'persona' => 'LOPEZ SANCHEZ LARISSA KARIME', 'generales' => null, 'adicionales' => null],
    ['id' => 85, 'persona' => 'LUIS GERARDO REYES SANCHEZ', 'generales' => null, 'adicionales' => null],
    ['id' => 86, 'persona' => 'LLANES JUAREZ JOSE TEODORO', 'generales' => null, 'adicionales' => null],
    ['id' => 87, 'persona' => 'MACIAS SANDOVAL JULIO', 'generales' => null, 'adicionales' => null],
    ['id' => 88, 'persona' => 'MANUEL JOSE MIER Y TERAN FORTUNI Y HERMANOS', 'generales' => null, 'adicionales' => null],
    ['id' => 89, 'persona' => 'MARIA EUGENIA MIER Y TERAN FORTUNY Y MARIA ISABEL MIER Y TERAN FORTUNI', 'generales' => null, 'adicionales' => null],
    ['id' => 90, 'persona' => 'MARIANELA LEAL QUINTAL', 'generales' => null, 'adicionales' => null],
    ['id' => 91, 'persona' => 'MARIN REJON ARIEL ARMANDO', 'generales' => null, 'adicionales' => null],
    ['id' => 92, 'persona' => 'MARRET MARY ANGELETTI Y MARRET LELAND TAYLOR', 'generales' => null, 'adicionales' => null],
    ['id' => 93, 'persona' => 'MARTINEZ PALMERO ISMAEL IGNACIO', 'generales' => null, 'adicionales' => null],
    ['id' => 94, 'persona' => 'MAY HOIL JUAN MANUEL Y OTROS', 'generales' => null, 'adicionales' => null],
    ['id' => 95, 'persona' => 'MEDINA VALDEZ MIGUEL GIDALTI', 'generales' => null, 'adicionales' => null],
    ['id' => 96, 'persona' => 'MENDIOLA LEON ILEANA RAVELL CANUL', 'generales' => null, 'adicionales' => null],
    ['id' => 97, 'persona' => 'MEX BALAM PAULINA MARCELA', 'generales' => null, 'adicionales' => null],
    ['id' => 98, 'persona' => 'MEX BALAM PAULINA MARCELA Y OTROS', 'generales' => null, 'adicionales' => null],
    ['id' => 99, 'persona' => 'MEX MAY JOSE BENITO Y BALAM CANCHE MARCELA SUC INT', 'generales' => null, 'adicionales' => null],
    ['id' => 100, 'persona' => 'MIER Y TERAN BOLIO LUIS FELIPE', 'generales' => null, 'adicionales' => null],
    ['id' => 101, 'persona' => 'MIER Y TERAN CAMARA MANUEL JOSE Y MENDIBURU FERNANDEZ ERIKA', 'generales' => null, 'adicionales' => null],
    ['id' => 102, 'persona' => 'MIER Y TERAN CAMARA RICARDO JOSE', 'generales' => null, 'adicionales' => null],
    ['id' => 103, 'persona' => 'MIER Y TERAN FORTUNY MANUEL JOSE', 'generales' => null, 'adicionales' => null],
    ['id' => 104, 'persona' => 'MIFEL', 'generales' => null, 'adicionales' => null],
    ['id' => 105, 'persona' => 'MIGUEL GIDALTI MEDINA VALDEZ', 'generales' => null, 'adicionales' => null],
    ['id' => 106, 'persona' => 'MOLINA DZIB MANUEL GASPAR - MOLINA MEX JOSE ALEJANDRO', 'generales' => null, 'adicionales' => null],
    ['id' => 107, 'persona' => 'MONICA JACQUELINE PACHECO FLORES', 'generales' => null, 'adicionales' => null],
    ['id' => 108, 'persona' => 'N/A', 'generales' => null, 'adicionales' => null],
    ['id' => 109, 'persona' => 'NOVELO MEDINA IVAN JOSE', 'generales' => null, 'adicionales' => null],
    ['id' => 110, 'persona' => 'NR FINANCE MEXICO S.A. DE C.V.', 'generales' => null, 'adicionales' => null],
    ['id' => 111, 'persona' => 'PAULINA MARCELA MEX BALAM Y ANGEL JESUS MASS COLLI', 'generales' => null, 'adicionales' => null],
    ['id' => 112, 'persona' => 'PECH MAGAÑA MARIA ANTONIA', 'generales' => null, 'adicionales' => null],
    ['id' => 113, 'persona' => 'PECH ONTIVEROS ROMAN DE JESUS', 'generales' => null, 'adicionales' => null],
    ['id' => 114, 'persona' => 'PERERA LOPEZ JAVIER FRANCISCO , CABRERA SOSA ANA CRISTINA Y PEREZ FRANCO JOSE ALBERTO', 'generales' => null, 'adicionales' => null],
    ['id' => 115, 'persona' => 'PEREZ FRANCO AURORA DE LOS ANGELES Y MIER Y TERAN FORTUNY MANUEL JOSE', 'generales' => null, 'adicionales' => null],
    ['id' => 116, 'persona' => 'PIÑA GARCIA IVETTE', 'generales' => null, 'adicionales' => null],
    ['id' => 117, 'persona' => 'POOL CHUC ERIK ALEJANDRO', 'generales' => null, 'adicionales' => null],
    ['id' => 118, 'persona' => 'POOT DZUL ESTEBAN FERNANDO', 'generales' => null, 'adicionales' => null],
    ['id' => 119, 'persona' => 'PORRAS PACHECO MANUEL', 'generales' => null, 'adicionales' => null],
    ['id' => 120, 'persona' => 'PRODUCTOS LOL CAB S.A. DE C.V. Y RAFAEL SOSA MONTALVO', 'generales' => null, 'adicionales' => null],
    ['id' => 121, 'persona' => 'PROMOVENTAS AL DETALLE S.A. DE C.V.', 'generales' => null, 'adicionales' => null],
    ['id' => 122, 'persona' => 'QUIÑONES MOO JOSE ALEJANDRO Y CHI COLLI MARIA LOURDES', 'generales' => null, 'adicionales' => null],
    ['id' => 123, 'persona' => 'RAMON GERARDO LOPEZ CASTILLO', 'generales' => null, 'adicionales' => null],
    ['id' => 124, 'persona' => 'REIG MURO SANDOVAL ARTURO', 'generales' => null, 'adicionales' => null],
    ['id' => 125, 'persona' => 'RENO DEL CARIBE SA DE CV - LUIS FELIPE BARCELO SOSA', 'generales' => null, 'adicionales' => null],
    ['id' => 126, 'persona' => 'REYES GILBERTO PECH CATZIN', 'generales' => null, 'adicionales' => null],
    ['id' => 127, 'persona' => 'RICARDO JOSE MIER Y TERAN', 'generales' => null, 'adicionales' => null],
    ['id' => 128, 'persona' => 'RIEGOS ESPECIALIZADOS DEL SURESTE SA DE CV / MEDINA VALDEZ MIGUEL GIDALTI', 'generales' => null, 'adicionales' => null],
    ['id' => 129, 'persona' => 'RIVAS ENCALADA ISABEL Y ALIAS', 'generales' => null, 'adicionales' => null],
    ['id' => 130, 'persona' => 'RODRIGUEZ RODRIGUEZ RUBEN DARIO', 'generales' => null, 'adicionales' => null],
    ['id' => 131, 'persona' => 'ROMERO RAMÓN RICARDO', 'generales' => null, 'adicionales' => null],
    ['id' => 132, 'persona' => 'ROSADO ARTEZAN MARIANA', 'generales' => null, 'adicionales' => null],
    ['id' => 133, 'persona' => 'RUBIO KU NALLIVE ISLANDA', 'generales' => null, 'adicionales' => null],
    ['id' => 134, 'persona' => 'SANCHEZ GONZALEZ ALBERTO', 'generales' => null, 'adicionales' => null],
    ['id' => 135, 'persona' => 'SANCHEZ UC ANGEL GABRIEL', 'generales' => null, 'adicionales' => null],
    ['id' => 136, 'persona' => 'SANTAMARIA BARREDO JONATHAN GILBERTO', 'generales' => null, 'adicionales' => null],
    ['id' => 137, 'persona' => 'SANTANDER', 'generales' => null, 'adicionales' => null],
    ['id' => 138, 'persona' => 'SCOTIABANK', 'generales' => null, 'adicionales' => null],
    ['id' => 139, 'persona' => 'SERRANO ARANA FERNANDO DE JESUS; y MARGARITA GUADALUPE MENDOZA RAMIREZ', 'generales' => null, 'adicionales' => null],
    ['id' => 140, 'persona' => 'SOSA CAMPOS MARTHA LEONOR Y ORTEGON XOOL OMAR ARTURO', 'generales' => null, 'adicionales' => null],
    ['id' => 141, 'persona' => 'SUCESION INTESTADA', 'generales' => null, 'adicionales' => null],
    ['id' => 142, 'persona' => 'TOCYAXUM S. DE P.R. DE R.L. DE C.V.', 'generales' => null, 'adicionales' => null],
    ['id' => 143, 'persona' => 'TORRE BOLIO MARIA CECILIA', 'generales' => null, 'adicionales' => null],
    ['id' => 144, 'persona' => 'TORRE MENENDEZ MARIA LORENA', 'generales' => null, 'adicionales' => null],
    ['id' => 145, 'persona' => 'TORRE MENENDEZ MARIA LORENA (sheeto)', 'generales' => null, 'adicionales' => null],
    ['id' => 146, 'persona' => 'TORRE MENENDEZ MARIA LORENA JOSE ALEJANDRO MOLINA MEX', 'generales' => null, 'adicionales' => null],
    ['id' => 147, 'persona' => 'TORRES CEN LORENZO', 'generales' => null, 'adicionales' => null],
    ['id' => 148, 'persona' => 'UC UCH SINFORIANO Y TAX CEME BERNARDINA', 'generales' => null, 'adicionales' => null],
    ['id' => 149, 'persona' => 'VALDEZ TEC JULIA ALICIA', 'generales' => null, 'adicionales' => null],
    ['id' => 150, 'persona' => 'VALERIA BERENICE BARGUEZ', 'generales' => null, 'adicionales' => null],
    ['id' => 151, 'persona' => 'VALLADARES GARZA JORGE FABIAN', 'generales' => null, 'adicionales' => null],
    ['id' => 152, 'persona' => 'VARGUEZ MENDEZ VALERIA BERENISE', 'generales' => null, 'adicionales' => null],
    ['id' => 153, 'persona' => 'VAZQUEZ MANZANO JORGE ANTONIO', 'generales' => null, 'adicionales' => null],
    ['id' => 154, 'persona' => 'VEGA DIAZ CARLOS FELIPE', 'generales' => null, 'adicionales' => null],
    ['id' => 155, 'persona' => 'VELAZQUEZ PULIDO JOSE MAURICIO', 'generales' => null, 'adicionales' => null],
    ['id' => 156, 'persona' => 'VICTOR MANUEL MELCHOR TUFIÑO', 'generales' => null, 'adicionales' => null],
    ['id' => 157, 'persona' => 'VILLANUEVA ABEL JESUS', 'generales' => null, 'adicionales' => null],
];
DB::table('personas')->insert($personas);  
    }
}
